### ISSUE TITLE
Syntax Error : unexpected token function

### ISSUE THREAD

**Issue by hussam-dh** [k4m4/dcipher-cli#3]
Hello @k4m4 ,
I installed dcipher and dcipher-cli but whenever I run dcipher I get This:

/usr/lib/node_modules/dcipher-cli/node_modules/dcipher/index.js:44
async function dcipherHash (hash, type) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/dcipher-cli/cli.js:6:20)

Thank you

**Comment by k4m4** [comment]
Hi there. Which versions of `node` and `npm` do you use?

**Comment by hussam-dh** [comment]
Hello,
so sorry for the delayed reply.
npm ->  3.10.10
node -> v6.12.0
Thanks

**Comment by k4m4** [comment]
Can you please try updating to node v9? Thanks again.

**Comment by hussam-dh** [comment]
Hello,
The package manager is not able to update it to more than this version,
so I think I should figure out how to do this manually.
thank you very much

**Comment by hussam-dh** [comment]
it is now working after updating both node and npm to the latest version.
thank you very much
